language: ruby
cache: bundler
sudo: false
rvm:
  - 2.3.3
  - 2.4.1
addons:
  apt:
    packages:
    - slapd
    - ldap-utils
    - unixodbc-dev
  postgresql: 9.4
before_script:
  - 'cp config/application.travis.yml config/application.yml'
  - "psql -c 'create database monitor_test;' -U postgres"
  - 'bundle exec rake db:migrate'
  - 'slapd -f test/fixtures/ldap/slapd.conf -h ldap://localhost:3389'
  - 'bundle exec rake ldap:reset'
