language: ruby
cache:
  directories:
    - $HOME/bundler
sudo: false
rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
addons:
  apt:
    packages:
    - slapd
    - ldap-utils
    - unixodbc-dev
  postgresql: 9.4
before_install:
  - 'gem install bundler'
before_script:
  - 'cp config/application.travis.yml config/application.yml'
  - "psql -c 'create database monitor_test;' -U postgres"
  - 'bundle exec rake db:migrate'
  - 'slapd -f test/fixtures/ldap/slapd.conf -h ldap://localhost:3389'
  - 'bundle exec rake ldap:reset'
install:
  - 'rm ${BUNDLE_GEMFILE}.lock'
  - 'eval bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}'
